"comment" = { fg = "taupe" }
"constant" = { fg = "coral" }
"function" = { fg = "mint" }
"function.macro" = { fg = "clay" }
"keyword" = { fg = "clay" }
"operator" = { fg = "clay" }
"punctuation" = { fg = "silk" }
"string" = { fg = "coral" }
"type" = { fg = "aqua" }
"variable" = { fg = "silk" }
"variable.builtin" = { fg = "aqua" }
"tag" = { fg = "mint" }
"label" = { fg = "coral" }
"attribute" = { fg = "silk" }
"namespace" = { fg = "silk" }
"module" = { fg = "silk" }
"markup.heading" = { fg = "coral", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "taupe" }
"markup.list" = { fg = "clay" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "aqua", modifiers = ["underlined"] }
"markup.link.text" = { fg = "aqua" }
"markup.quote" = { fg = "taupe" }
"markup.raw" = { fg = "mint" }
"ui.background" = { bg = "carbon" }
"ui.cursor" = { fg = "carbon", bg = "silk" }
"ui.cursor.match" = { modifiers = ["bold"] }
"ui.cursor.select" = { fg = "carbon", bg = "aqua" }
"ui.cursor.insert" = { fg = "carbon", bg = "mint" }
"ui.linenr" = { fg = "taupe" }
"ui.linenr.selected" = { fg = "silk" }
"ui.cursorline" = { fg = "silk", bg = "dusty_taupe" }
"ui.statusline" = { fg = "silk", bg = "graphite" }
"ui.statusline.inactive" = { fg = "taupe", bg = "graphite" }
"ui.statusline.normal" = { fg = "graphite", bg = "silk", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "graphite", bg = "mint", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "graphite", bg = "aqua", modifiers = ["bold"] }
"ui.bufferline" = { fg = "silk", bg = "graphite" }
"ui.bufferline.active" = { fg = "graphite", bg = "silk" }
"ui.popup" = { fg = "silk", bg = "graphite" }
"ui.window" = { fg = "taupe", bg = "carbon" }
"ui.help" = { fg = "silk", bg = "graphite" }
"ui.text" = { fg = "silk" }
"ui.text.focus" = { fg = "coral", bg = "graphite" }
"ui.menu" = { fg = "silk", bg = "graphite" }
"ui.menu.selected" = { fg = "graphite", bg = "silk" }
"ui.selection" = { bg = "graphite" }
"ui.virtual.whitespace" = { fg = "taupe" }
"ui.virtual.ruler" = { bg = "dusty_taupe" }
"ui.virtual.indent-guide" = { fg = "brown" }
"ui.virtual.inlay-hint" = { fg = "taupe" }
"ui.virtual.jump-label" = { fg = "gold", modifiers = ["bold"] }
"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "blue" }
"diff.minus" = { fg = "red" }
"error" = { fg = "red" }
"warning" = { fg = "gold" }
"info" = { fg = "blue" }
"hint" = { fg = "blue" }
"diagnostic.warning" = { underline = { color = "gold", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
carbon = "#262727"
brown = "#5A524F"
gold = "#F5C462"
graphite = "#343231"
taupe = "#837270"
dusty_taupe = "#A48C76"
clay = "#F2BA86"
coral = "#EC9898"
silk = "#F0D3C9"
mint = "#84D2C5"
aqua = "#C0F9FF"
red = "#F2515E"
green = "#6CE0B4"
blue = "#83BCFF"
