# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Custom format
format = """$os [$username]()[at](bold green) ($directory)($git_branch)($git_status)$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Shows the username
[username]
style_user = "white"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 50
truncate_to_repo = true
style = "yellow"
home_symbol = "home"
read_only_style = "197"
read_only = ""
format = "[$path]($style)[$read_only]($read_only_style) "

[line_break]
disabled = true

[character]
success_symbol = "[⤏](bold green)"
error_symbol   = "[⤏](bold red)"

[git_branch]
format = "via [$branch]($style) "
truncation_length = 50
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '$all_status$ahead_behind'
ahead = '[⬆](bold purple) '
behind = '[⬇](bold purple) '
staged = '[✚](green) '
deleted = '[✖](red) '
renamed = '[➜](purple) '
stashed = '[✭](bold cyan) '
untracked = '[⛯](bold white) '
modified = '[✱](blue) '
conflicted = '[═](bold yellow) '
diverged = '[⇕](bold cyan) '
up_to_date = ''






