# Inserts a blank line between shell prompts
add_newline = false

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
format = """\
[╭╴](238)$env_var\
$all[╰─](238)$character"""
# 

# Change the default prompt characters
[character]
success_symbol = " [λ](grey)"
error_symbol = " [](bold red)"


# Shows the username
[username]
style_user = "white"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 50
truncate_to_repo = false
style = "yellow"
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "


[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
truncation_length = 50
truncation_symbol = "…/"
style = "bold green"


[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[git_metrics]
disabled = false
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[docker_context]
format = "via [ $context](blue bold)"

[dart]
format = "via [ $version](bold cyan) "

[golang]
format = "via [ $version](bold cyan) "

[dotnet]
symbol = " "
style = "green"
heuristic = false

[kotlin]
symbol = "🅺 "
kotlin_binary = "kotlinc"


[kubernetes]
format = 'on [ﴱ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
[kubernetes.user_aliases]
"dev.local.cluster.k8s" = "dev"
"root/.*" = "root"

[nodejs]
format = "via [ $version](bold green) "

[package]
format = "via [ $version](208 bold) "

