# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Custom format
format = """($directory)($git_branch)($git_status)$character"""

# Inserts a blank line between shell prompts
add_newline = false

[directory]
truncation_length = 50
truncate_to_repo = true
style = "yellow"
home_symbol = "~"
read_only_style = "197"
read_only = ""
format = "[$path]($style)[$read_only]($read_only_style) "

[line_break]
disabled = true

[character]
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"

[git_branch]
format = 'via [$branch](bold #7695FF)'
truncation_length = 50
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = ' ([\( $all_status$ahead_behind\) ]($style))'
ahead = '[⬆](bold purple) ${count} '
behind = '[⬇](bold purple) ${count} '
staged = '[✚](blue) ${count} '
deleted = '[✖](red) ${count} '
renamed = '[⭮](bold purple) ${count} '
stashed = '[𝌤](bold cyan) ${count} '
untracked = '[🞋](bold red) ${count} '
modified = '[✱](yellow) ${count} '
conflicted = '[⇼](bold red) ${count} '
diverged = '[🢰](bold cyan) ${count} '
up_to_date = ' '
